# このファイルはテンプレートとして使用します。
# 実際の値はCI/CDパイプラインで動的に設定され、Base64エンコードされます。
apiVersion: v1
kind: Secret
metadata:
  name: wiz-app-secrets
type: Opaque
data:
  # CI/CDパイプラインで以下の値を設定する
  # echo -n 'mongodb://wizadmin:your-password@internal-ip:27017' | base64
  MONGODB_URI: "" # 例: bW9uZ29kYjovL3dpemFkbWluOnlvdXItcGFzc3dvcmRAaW50ZXJuYWwtaXA6MjcwMTc=
  # echo -n 'a-very-secure-and-random-jwt-secret-key' | base64
  SECRET_KEY: "" # 例: YS12ZXJ5LXNlY3VyZS1hbmQtcmFuZG9tLWp3dC1zZWNyZXQta2V5
