# 注意: Base64エンコードされた値を直接コミットするのは避けるべき
# 本番環境ではSecret Managerなどの外部ストアを利用
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # vm.tfの起動スクリプトで設定したユーザー名とパスワード、およびTerraformの出力値を使用する
  # MONGO_URI: "mongodb://todoapp:TodoPassword123!@<mongodb_internal_ip>:27017/tododb"
  MONGO_URI: "mongodb://todoapp:TodoPassword123!@10.0.2.2:27017/tododb" # Terraformの出力値 `mongodb_internal_ip` に置き換えて