apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiz-app-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wiz-app-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # 権限が強力すぎるので、本番環境では要注意
subjects:
- kind: ServiceAccount
  name: wiz-app-sa
  namespace: default