apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiz-app
  template:
    metadata:
      labels:
        app: wiz-app
    spec:
      # ★★★ 要件: クラスタ全体の管理者ロールを付与 ★★★
      serviceAccountName: cluster-admin-sa # 01-rbac.yamlで作成するServiceAccount
      containers:
      - name: wiz-app
        # ★★★ CI/CDパイプラインでビルドしたイメージを指定 ★★★
        image: __IMAGE_PLACEHOLDER__  
        ports:
        - containerPort: 8080
        env:
        # ★★★ Secretから環境変数を設定 ★★★
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: wiz-app-secrets # 00-secret.yamlで作成したSecret名
              key: MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: wiz-app-secrets
              key: SECRET_KEY