apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort # Ingress Controllerがトラフィックを受け取れるようにNodePortまたはClusterIPを使用