# .github/workflows/deploy-app.yml

name: Deploy Application to GKE

# ワークフローのトリガー設定
on:
  # 1. mainブランチの app/ または k8s/ ディレクトリにプッシュされたときに自動実行
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'k8s/**'
  
  # 2. GitHubのActionsタブから手動で実行できるようにする
  workflow_dispatch:

# ワークフロー全体で使用する環境変数を定義
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: wiz-gke-cluster
  GKE_REGION: asia-northeast1
  GKE_ZONE: asia-northeast1-a
  REPO_NAME: wiz-repo
  IMAGE_NAME: wiz-app
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # 1. リポジトリのコードをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Google Cloudへの認証
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    # 3. gcloud CLIをセットアップ
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    # 4. GKEクラスタの認証情報を取得
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_REGION }}

    # 5. DockerイメージをビルドしてArtifact Registryにプッシュ
    - name: Build and Push Docker image
      run: |
        gcloud auth configure-docker ${{ env.GKE_REGION }}-docker.pkg.dev
        docker build -t ${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f app/Dockerfile ./
        docker push ${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    # 6. ★★★ 修正: 認証情報をハードコードしてKubernetes Secretを作成 (非推奨) ★★★
    - name: Create/Update Kubernetes Secrets
      id: create-secrets
      run: |
        set -euo pipefail
        
        # VMのホスト名は静的
        MONGO_HOSTNAME="mongodb-vm"

        # ★★★ アンチパターン: 認証情報を直接コードに記述 ★★★
        # 注意: この方法は安全ではありません。演習の簡素化のためだけに使用してください。
        # パスワードはVMの起動スクリプトで設定したものと一致させる必要があります。
        MONGO_URI="mongodb://wizadmin:wizpassword@${MONGO_HOSTNAME}:27017/todo_db?authSource=admin"
        JWT_KEY="secret123"
        
        echo "Constructed MONGODB_URI (password hidden): mongodb://wizadmin:***@${MONGO_HOSTNAME}:27017/todo_db?authSource=admin"

        # Kubernetes Secretを作成（存在すれば更新）
        kubectl create secret generic wiz-app-secrets \
          --from-literal=MONGODB_URI="${MONGO_URI}" \
          --from-literal=SECRET_KEY="${JWT_KEY}" \
          --dry-run=client -o yaml | kubectl apply -f -

    # 7. KubernetesマニフェストをGKEにデプロイ
    - name: Deploy to GKE
      run: |
        FULL_IMAGE_PATH="${{ env.GKE_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        sed -i "s|image: __IMAGE_PLACEHOLDER__|image: ${FULL_IMAGE_PATH}|g" k8s/02-deployment.yaml
        kubectl apply -f k8s/

    # 8. 実行中のコンテナ内でwizexercise.txtの存在と内容を検証
    - name: Verify wizexercise.txt in running container
      id: verify-pod
      run: |
        echo "Waiting for new pods to be ready..."
        kubectl wait --for=condition=ready pod -l app=wiz-app --timeout=120s
        
        POD_NAME=$(kubectl get pods -l app=wiz-app -o jsonpath='{.items[0].metadata.name}')
        
        echo "Verifying content of wizexercise.txt in pod: $POD_NAME"
        kubectl exec $POD_NAME -- cat /app/wizexercise.txt

    # 9. Podの準備が失敗した場合にデバッグ情報を出力
    - name: Debug Pods on Failure
      if: failure() && steps.verify-pod.conclusion == 'failure'
      run: |
        echo "::error::Pod verification failed. Collecting debug information..."
        echo "--- Pods Status ---"
        kubectl get pods -l app=wiz-app -o wide
        
        POD_NAMES=$(kubectl get pods -l app=wiz-app -o jsonpath='{.items[*].metadata.name}')
        for POD_NAME in $POD_NAMES; do
          echo "--- Describing pod: $POD_NAME ---"
          kubectl describe pod $POD_NAME
          echo "--- Logs from pod: $POD_NAME ---"
          kubectl logs $POD_NAME --all-containers=true
        done
